# Generated by Django 6.0 on 2025-12-23 09:21

import apps.accounts.models
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите ваше имя', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите вашу фамилию', max_length=100, verbose_name='Фамилия')),
                ('father_name', models.CharField(blank=True, help_text='Введите отчество (необязательно)', max_length=50, null=True, verbose_name='Отчество')),
                ('company', models.CharField(blank=True, help_text='Название вашей компании', max_length=255, null=True, verbose_name='Компания')),
                ('position', models.CharField(blank=True, help_text='Ваша должность в компании', max_length=255, null=True, verbose_name='Должность')),
                ('birth_date', models.DateField(blank=True, help_text='Формат: ГГГГ-ММ-ДД', null=True, verbose_name='Дата рождения')),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Выберите вашу страну', max_length=2, null=True, verbose_name='Страна')),
                ('address', models.TextField(blank=True, help_text='Полный адрес проживания', null=True, verbose_name='Адрес')),
                ('passport_number', models.CharField(blank=True, help_text='Номер вашего паспорта', max_length=50, null=True, verbose_name='Номер паспорта')),
                ('passport_issue_date', models.DateField(blank=True, help_text='Формат: ГГГГ-ММ-ДД', null=True, verbose_name='Дата выдачи паспорта')),
                ('passport_expiry_date', models.DateField(blank=True, help_text='Формат: ГГГГ-ММ-ДД', null=True, verbose_name='Дата окончания паспорта')),
                ('education_degree', models.CharField(blank=True, choices=[('bachelor', "Bachelor's"), ('master', "Master's"), ('phd', 'PhD'), ('other', 'Other')], help_text="Например: Bachelor's, Master's", max_length=100, null=True, verbose_name='Степень образования')),
                ('education_institute', models.CharField(blank=True, help_text='Название университета или колледжа', max_length=255, null=True, verbose_name='Учебное заведение')),
                ('specialization', models.CharField(blank=True, help_text='Ваша специализация или факультет', max_length=255, null=True, verbose_name='Специализация')),
                ('website', models.URLField(blank=True, help_text='Если есть личный сайт или компания', null=True, verbose_name='Веб-сайт')),
                ('photo', models.ImageField(blank=True, help_text='Загрузите ваше фото', null=True, upload_to=apps.accounts.models.photo_path, verbose_name='Фото')),
                ('passport_copy', models.FileField(blank=True, help_text='Загрузите скан вашего паспорта', null=True, upload_to=apps.accounts.models.passport_copy_path, verbose_name='Копия паспорта')),
                ('employment_verification', models.FileField(blank=True, help_text='Загрузите подтверждение занятости', null=True, upload_to=apps.accounts.models.employment_verification_path, verbose_name='Справка с работы')),
                ('user', models.OneToOneField(help_text='Связанный аккаунт пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
