# Generated by Django 6.0 on 2025-12-29 07:35

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diploma_scan',
            field=models.FileField(blank=True, help_text='Загрузите скан вашего диплома', null=True, upload_to=apps.accounts.models.diploma_scan_path, verbose_name='Скан диплома'),
        ),
    ]
