# Generated by Django 6.0 on 2025-12-29 11:46

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_diploma_scan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Введите инфомрацию о вашей компании', null=True, verbose_name='О компании')),
                ('img', models.ImageField(blank=True, help_text='Загрузите логотип вашей компании', null=True, upload_to=apps.accounts.models.logo_path, verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи', verbose_name='Дата обновления')),
            ],
        ),
    ]
