# Generated by Django 6.0 on 2025-12-29 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_catalogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogentry',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='accounts.profile', verbose_name='Профиль'),
            preserve_default=False,
        ),
    ]
