# Generated by Django 6.0 on 2026-01-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_catalogentry_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_paid_delegate_fee',
            field=models.BooleanField(default=False, verbose_name='Оплатил делегатский взнос'),
        ),
        migrations.AddField(
            model_name='profile',
            name='visa_processed',
            field=models.BooleanField(default=False, verbose_name='Подача на визу обработана'),
        ),
    ]
