# Generated by Django 6.0 on 2026-01-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_has_paid_delegate_fee_profile_visa_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='need_visa',
            field=models.BooleanField(default=False, help_text='Does the user require a visa', verbose_name='Needs visa'),
        ),
    ]
