# Generated by Django 6.0 on 2026-01-14 05:37

import apps.accounts.models
import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_need_visa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='diploma_scan',
            field=models.FileField(blank=True, help_text='Загрузите скан вашего диплома', null=True, upload_to=apps.accounts.models.diploma_scan_path, validators=[apps.accounts.validators.validate_file_size], verbose_name='Скан диплома'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employment_verification',
            field=models.FileField(blank=True, help_text='Загрузите подтверждение занятости', null=True, upload_to=apps.accounts.models.employment_verification_path, validators=[apps.accounts.validators.validate_file_size], verbose_name='Справка с работы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_copy',
            field=models.FileField(blank=True, help_text='Загрузите скан вашего паспорта', null=True, upload_to=apps.accounts.models.passport_copy_path, validators=[apps.accounts.validators.validate_file_size], verbose_name='Копия паспорта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите ваше фото', null=True, upload_to=apps.accounts.models.photo_path, validators=[apps.accounts.validators.validate_file_size], verbose_name='Фото'),
        ),
    ]
