# Generated by Django 6.0 on 2026-01-23 05:23

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_diploma_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Укажите номер в международном формате, например: +99361234567', max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
    ]
