# Generated by Django 6.0 on 2026-01-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education_degree',
            field=models.CharField(blank=True, choices=[('bachelor', "Bachelor's"), ('master', "Master's"), ('phd', 'PhD'), ('secondary', 'Secondary'), ('secondary_professional', 'Secondary professional')], help_text="Например: Bachelor's, Master's", max_length=100, null=True, verbose_name='Степень образования'),
        ),
    ]
