# Generated by Django 6.0 on 2026-01-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка'),
        ),
    ]
