# Generated by Django 6.0 on 2025-12-26 05:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_about_alter_intro_video_abouttranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='tabs_images/%Y/%m/%d', verbose_name='Tab Image')),
            ],
        ),
        migrations.AlterField(
            model_name='abouttranslation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
