# Generated by Django 6.0 on 2026-01-23 11:46

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_partner_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Загрузите PDF файл', upload_to='files/', verbose_name='PDF файл')),
                ('resource_type', models.CharField(choices=[('brochure', 'Брошюра'), ('travel_guide', 'Тревел-гайд')], default='brochure', max_length=50, verbose_name='Тип ресурса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PDF ресурс',
                'verbose_name_plural': 'PDF ресурсы',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FileResourceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название файла')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.fileresource')),
            ],
            options={
                'verbose_name': 'PDF ресурс Translation',
                'db_table': 'core_fileresource_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
