# Generated by Django 6.0 on 2026-01-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fileresource_fileresourcetranslation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileresource',
            options={'ordering': ['-created_at'], 'verbose_name': 'File Resource', 'verbose_name_plural': 'File Resources'},
        ),
        migrations.AlterModelOptions(
            name='fileresourcetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'File Resource Translation'},
        ),
        migrations.RemoveField(
            model_name='fileresource',
            name='file',
        ),
        migrations.AddField(
            model_name='fileresourcetranslation',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a PDF file for this language', null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='fileresource',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fileresource',
            name='resource_type',
            field=models.CharField(choices=[('brochure', 'Brochure'), ('travel_guide', 'Travel Guide')], default='brochure', max_length=50),
        ),
        migrations.AlterField(
            model_name='fileresourcetranslation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileresourcetranslation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
