# Generated by Django 6.0 on 2026-01-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_fileresource_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileresource',
            name='resource_type',
            field=models.CharField(choices=[('brochure', 'Brochure'), ('travel_guide', 'Travel Guide'), ('off_support', 'Official Support')], default='brochure', max_length=50),
        ),
    ]
