# Generated by Django 6.0 on 2025-12-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_partnerlevel_alter_partner_logo_partner_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerlevel',
            name='slug',
            field=models.SlugField(default=11, help_text='Используется для CSS классов (gold, silver, bronze)', unique=True),
            preserve_default=False,
        ),
    ]
