# Generated by Django 6.0 on 2026-02-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_fileresource_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileresource',
            name='resource_type',
            field=models.CharField(choices=[('brochure', 'Brochure'), ('travel_guide', 'Travel Guide'), ('off_support', 'Official Support'), ('meet_req', 'Meeting Request')], default='brochure', max_length=50),
        ),
    ]
