# Generated by Django 6.0 on 2026-02-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_fileresource_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число — тем выше отображается', verbose_name='Порядок'),
        ),
    ]
