# Generated by Django 6.0 on 2026-02-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sponsortype_alter_fileresource_resource_type_sponsor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsortype',
            name='slug',
        ),
    ]
