# Generated by Django 6.0 on 2026-02-24 07:32

import apps.core.models
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_fileresource_resource_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.core.models.investment_cover_path, verbose_name='Обложка')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.core.models.investment_file_path, verbose_name='PDF файл')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше отображение', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Инвестмент',
                'verbose_name_plural': 'Инвестменты',
                'ordering': ['order', 'created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InvestmentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Название инвестмента')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.investment')),
            ],
            options={
                'verbose_name': 'Инвестмент Translation',
                'db_table': 'core_investment_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
