# Generated by Django 6.0 on 2026-02-25 07:02

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_investment_investmenttranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='second_cover',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.models.investment_cover_path, verbose_name='Обложка'),
        ),
    ]
