# Generated by Django 6.0 on 2026-02-25 07:36

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_investment_second_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='file',
        ),
        migrations.AddField(
            model_name='investmenttranslation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.models.investment_file_path, verbose_name='PDF файл'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='second_cover',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.models.investment_cover_path, verbose_name='Обложка под другой'),
        ),
    ]
