# Generated by Django 6.0 on 2026-02-25 12:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_investment_file_investmenttranslation_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectortranslation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание сектора'),
        ),
    ]
