# Generated by Django 6.0 on 2026-01-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_alter_persontranslation_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontranslation',
            name='session',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
